[versions]
coreKtx = "1.17.0"
lifecycleRuntimeKtx = "2.10.0"
lottieCompose = "6.7.1"
composeBom = "2025.11.01"
activityCompose = "1.12.0"
hilt = "2.57.2"
hiltNavigationCompose = "1.3.0"
navigationCompose = "2.9.6"
kotlinxSerializationJson = "1.8.0"
neumorphic = "0.0.6"
materialIconsExtended = "1.7.8"
textGoogleFonts = "1.9.5"

[libraries]

#Core
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

#Dependency Injection
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt"}
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt"}
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose"}

#Compose
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
ui-text-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "textGoogleFonts"}
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose"}

#UI
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose"}
neumorphic = { module = "io.github.sridhar-sp:neumorphic", version.ref = "neumorphic"}
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended"}


[bundles]

[plugins]
